[package]
name = "bitcoin-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39-last-word = { path = "../bip39-last-word" }
slint = { version = "1.16.1", default-features = false, features = [
    "libm",
    "unsafe-single-threaded",
    "compat-1-2",
    "renderer-software",
] }

[build-dependencies]
bip39 = { version = "2.2.2", default-features = false, features = ["chinese-simplified"] }
slint-build = { version = "1.16.1", features = ["sdf-fonts"] }
